## Importando o cliente

In [1]:
from core.ckan_api_reader import Ckan

In [2]:
CKAN_DOMAIN = "https://repositorio.seade.gov.br/api/3/"

In [3]:
ckan = Ckan(CKAN_DOMAIN)

In [4]:
ckan.pkgs

{'agricultura-municipal',
 'anexo-metodologico-populacao',
 'anexos-metodologicos-seade-municipios',
 'aprovacao-escolar-por-municipio-ano-nivel-de-ensino-e-rede-de-atendimento',
 'casamentos',
 'cnae-20',
 'codigos-nomes-dos-distritos-do-municipio-de-sao-paulo',
 'comercio-exterior',
 'comercio-exterior-nos-municipios',
 'covid-19',
 'demografia',
 'domicilios-estado-de-sao-paulo',
 'economia',
 'educacao-basica-painel',
 'educacao-do-ensino-superior',
 'emprego-formal-2021-painel',
 'emprego-formal-ocupacoes',
 'emprego-rais-e-arquivos-auxiliares',
 'equipamento',
 'estabelecimentos-de-saude',
 'estatisticas-vitais',
 'estatisticas-vitais-microdados',
 'ideb',
 'indice-paulista-de-desenvolvimento-municipal-ipdm',
 'informacoes-municipais',
 'infraestrutura-e-meio-ambiente',
 'leitos-hospitalares-por-municipio-por-ano',
 'limites-e-regioes',
 'matriculas-por-municipio-ano-nivel-de-ensino-e-rede-de-atendimento',
 'medicos-e-enfermeiros-por-municipio-ano-e-rede-de-atendimento',
 'microdados-casamentos',
 'microdados-nascidos-vivos',
 'microdados-obitos',
 'mortalidade-infantil',
 'mortalidade-no-estado-de-sao-paulo',
 'municipios',
 'nascidos-vivos',
 'nascidos-vivos-municipio-de-sao-paulo',
 'nomes-codigos-municipios-esp',
 'obitos',
 'obitos-municipio-de-sao-paulo',
 'ocupacao-e-rendimento',
 'painel-economia-agropecuaria',
 'pecuaria-municipal',
 'pesquisa-de-cuidados-no-domicilio',
 'pib-anual-2002-2020',
 'pib-mensal',
 'pib-municipal-2002-2020',
 'pib-regional',
 'pib-trimestral',
 'populacao-do-municipio-de-sao-paulo-por-distrito-e-idade-escolar',
 'populacao-do-municipio-de-sao-paulo-por-distrito-e-porte-populacional',
 'populacao-do-municipio-de-sp-por-distritos',
 'populacao-municipal-2010-2022',
 'populacao-municipal-por-sexo-e-idade-2010-2021',
 'populacao-por-municipio-de-idade-escolar',
 'populacao-residente-estado-de-sao-paulo',
 'populacao-residente-estado-de-sao-paulo-evolucao',
 'populacao-residente-municipio-de-sao-paulo',
 'populacao-residente-municipio-de-sao-paulo-evolucao',
 'populacao-total-2021-e-idadessimples',
 'populacao-urbana-e-rural',
 'projecao-da-populacao-do-estado-de-sao-paulo-por-idade-2021',
 'projecao-da-populacao-por-municipio-idade-escolar-sexo-e-ano',
 'projecao-da-populacao-por-municipio-idade-sexo-e-ano-2010-2021',
 'saneamento-estado-de-sao-paulo-e-brasil',
 'saude-painel',
 'seade-censo-2022',
 'seade-fecundidade',
 'seade-industria',
 'seade-investimentos',
 'seade-investimentos-anexos-metodologicos',
 'seade-painel',
 'seade-trajetorias-ocupacionais',
 'social',
 'trajetorias-ocupacionais-anexos-metodologicos',
 'transferencia-de-renda-painel',
 'valor-de-transformacao-industrial-nos-municipios'}

## Fazendo download dos dados

In [5]:
res = ckan('microdados-casamentos', search_string='2021', attr='name', how='contains', as_list=True, extract=True, parser_params={'sep': ';'})

In [11]:
res

,anoreferencia,codmunreg,dtregistro,dtcasamento,diasemcas,tipocas,sexocj1,sexocj2,estcivcj1,estcivcj2,...,naturalcj2,codrescj1,codrescj2,idadecj1,idadecj2,casantecj1,casantecj2,filhoscj1,filhoscj2,fonte
0,2021,3550308,9012021,9012021,7,C,1,2,1,1,...,9800392,3550308,3550308,32,25,0,0,0,0,SEADE
1,2021,3550308,9012021,9012021,7,C,1,2,1,1,...,9800032,3550308,3550308,23,45,0,0,99,99,SEADE
2,2021,3550308,9012021,9012021,7,C,1,2,1,3,...,3550308,3550308,3550308,41,39,0,99,99,99,SEADE
3,2021,3550308,9012021,9012021,7,C,1,2,3,3,...,2402600,3548708,3550308,42,48,99,99,99,99,SEADE
4,2021,3550308,9012021,9012021,7,C,1,2,1,1,...,9800332,3550308,3550308,32,36,0,0,99,99,SEADE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231689,2021,3515350,20122021,20122021,2,C,1,2,1,1,...,3534401,3515350,3515350,60,47,0,0,0,0,SEADE
231690,2021,3515350,22122021,22122021,4,C,1,2,3,1,...,4127304,3515350,3515350,29,43,99,0,0,0,SEADE
231691,2021,3537156,10122021,10122021,6,C,1,2,3,3,...,3528809,3537156,3537156,22,26,1,1,0,0,SEADE
231692,2021,3537156,11122021,11122021,7,C,1,2,1,1,...,3528809,3504008,3537156,25,24,0,0,0,0,SEADE
231693,2021,3537156,11122021,11122021,7,C,1,2,1,1,...,3510005,3537156,3537156,21,21,0,0,0,0,SEADE

In [13]:
res.to_csv('arquivo.csv', sep=';', index=False)